ALTER TABLE PRODUTO ADD PROMO_ATIVA CHAR(1);

-- Tabela de Regras
CREATE TABLE REGRAS_PROMOCAO (
    ID INTEGER NOT NULL PRIMARY KEY,
    COD_SEC INTEGER NOT NULL, -- Agora referenciando Sessão
    DIAS_SEMANA VARCHAR(20),
    DATA_FIXA DATE,
    STATUS VARCHAR(10) DEFAULT 'NORMAL'
);

-- 2. Criar o Generator (o contador)
CREATE GENERATOR GEN_REGRAS_PROMOCAO_ID;
SET GENERATOR GEN_REGRAS_PROMOCAO_ID TO 0;


SET TERM ^ ;
CREATE OR ALTER TRIGGER TRG_REGRAS_PROMOCAO_BI FOR REGRAS_PROMOCAO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  -- Se o ID vier vazio do Python, o Generator assume
  IF (NEW.ID IS NULL OR NEW.ID = 0) THEN
    NEW.ID = GEN_ID(GEN_REGRAS_PROMOCAO_ID, 1);
END^
SET TERM ; ^



SET TERM ^ ;
-- PROCEDURE PARA ATIVAR
CREATE OR ALTER PROCEDURE SP_ATIVAR_PROMO_SECAO (VAR_SEC INTEGER)
AS
BEGIN
    -- Ativa a promoção para os produtos da seção que possuem preço promocional > 0
    UPDATE PRODUTO 
    SET PROMO_ATIVA = 'S'
    WHERE COD_SEC = :VAR_SEC 
      AND PRECO_PROMOCAO > 0;
END^

-- PROCEDURE PARA DESATIVAR
CREATE OR ALTER PROCEDURE SP_DESATIVAR_PROMO_SECAO (VAR_SEC INTEGER)
AS
BEGIN
    -- Desativa a promoção para todos os produtos da seção
    UPDATE PRODUTO 
    SET PROMO_ATIVA = 'N'
    WHERE COD_SEC = :VAR_SEC;
END^
SET TERM ; ^



----------------


SET TERM ^ ;

-- 1. PROCEDURE PARA VERIFICAR E ATIVAR
CREATE OR ALTER PROCEDURE SP_ROTINA_ATIVAR_PROMO
AS
DECLARE VARIABLE VAR_SEC INTEGER;
DECLARE VARIABLE VAR_DIA_SEM INTEGER;
BEGIN
    VAR_DIA_SEM = EXTRACT(WEEKDAY FROM CURRENT_DATE);

    -- Busca regras que batem com hoje (Data Fixa OU Dia da Semana) e estão inativas
    FOR SELECT COD_SEC FROM REGRAS_PROMOCAO 
        WHERE STATUS = 'NORMAL' 
        AND (DATA_FIXA = CURRENT_DATE OR DIAS_SEMANA LIKE '%' || :VAR_DIA_SEM || '%')
        INTO :VAR_SEC
    DO
    BEGIN
        -- Ativa os produtos daquela seção
        UPDATE PRODUTO SET PROMO_ATIVA = 'S' 
        WHERE COD_SEC = :VAR_SEC AND PRECO_PROMOCAO > 0;
        
        -- Marca a regra como ATIVA
        UPDATE REGRAS_PROMOCAO SET STATUS = 'PROMO' WHERE COD_SEC = :VAR_SEC;
    END
END^

-- 2. PROCEDURE PARA VERIFICAR E DESATIVAR
CREATE OR ALTER PROCEDURE SP_ROTINA_DESATIVAR_PROMO
AS
DECLARE VARIABLE VAR_SEC INTEGER;
DECLARE VARIABLE VAR_DIA_SEM INTEGER;
BEGIN
    VAR_DIA_SEM = EXTRACT(WEEKDAY FROM CURRENT_DATE);

    -- Busca regras que estão como 'PROMO' mas NÃO deveriam estar ativas hoje
    FOR SELECT COD_SEC FROM REGRAS_PROMOCAO 
        WHERE STATUS = 'PROMO'
        AND (
            (DATA_FIXA IS NOT NULL AND DATA_FIXA <> CURRENT_DATE) OR 
            (DIAS_SEMANA IS NOT NULL AND DIAS_SEMANA NOT LIKE '%' || :VAR_DIA_SEM || '%')
        )
        INTO :VAR_SEC
    DO
    BEGIN
        -- Desativa os produtos
        UPDATE PRODUTO SET PROMO_ATIVA = 'N' WHERE COD_SEC = :VAR_SEC;
        
        -- Volta a regra para status NORMAL
        UPDATE REGRAS_PROMOCAO SET STATUS = 'NORMAL' WHERE COD_SEC = :VAR_SEC;
    END
END^
SET TERM ; ^

-----------------------------


SELECT * FROM PRODUTO WHERE COD_PRO = 5;
SELECT * FROM REGRAS_PROMOCAO; 