ALTER TABLE PRODUTO ADD PROMO_ATIVA CHAR(1);
ALTER TABLE PRODUTO ADD CODIGO_EXTERNO VARCHAR(30);
ALTER TABLE PRODUTO ADD ULTIMA_ALTERACAO TIMESTAMP;
DROP GENERATOR GEN_REGRAS_PROMOCAO_ID;

CREATE TABLE CONTROLE_SYNC_LOCAL (
    ID INTEGER NOT NULL PRIMARY KEY,
    ULTIMA_ATUALIZACAO_RECEBIDA TIMESTAMP,
    ULTIMA_ATUALIZACAO_ENVIADA TIMESTAMP
);

-- Inicializa
INSERT INTO CONTROLE_SYNC_LOCAL (ID, ULTIMA_ATUALIZACAO_RECEBIDA, ULTIMA_ATUALIZACAO_ENVIADA)
VALUES (1, '2020-01-01 00:00:00', '2020-01-01 00:00:00');

SET TERM ^ ;

CREATE OR ALTER TRIGGER TG_PRODUTO_BU FOR PRODUTO
ACTIVE BEFORE UPDATE POSITION 0
AS
BEGIN
    NEW.ULTIMA_ALTERACAO = CURRENT_TIMESTAMP;
END^

CREATE OR ALTER TRIGGER TG_PRODUTO_BI FOR PRODUTO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.ULTIMA_ALTERACAO IS NULL) THEN
        NEW.ULTIMA_ALTERACAO = CURRENT_TIMESTAMP;
END^

SET TERM ; ^

