SELECT * FROM PRODUTO WHERE COD_PRO = 100;
SELECT * FROM REGRAS_PROMOCAO; 

-- Coluna de backup no cadastro de produtos
ALTER TABLE PRODUTO ADD PRECO_NORMAL NUMERIC(18,2);

-- Tabela de Regras
CREATE TABLE REGRAS_PROMOCAO (
    ID INTEGER NOT NULL PRIMARY KEY,
    COD_SEC INTEGER NOT NULL, -- Agora referenciando Sessão
    DIAS_SEMANA VARCHAR(20),
    DATA_FIXA DATE,
    STATUS VARCHAR(10) DEFAULT 'NORMAL'
);

-- 2. Criar o Generator (o contador)
CREATE GENERATOR GEN_REGRAS_PROMOCAO_ID;
SET GENERATOR GEN_REGRAS_PROMOCAO_ID TO 0;

-- Re-criar o Generator e Trigger (se seu Firebird for anterior ao 3.0)
CREATE GENERATOR GEN_REGRAS_PROMOCAO_ID;

SET TERM ^ ;
CREATE OR ALTER TRIGGER TRG_REGRAS_PROMOCAO_BI FOR REGRAS_PROMOCAO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  -- Se o ID vier vazio do Python, o Generator assume
  IF (NEW.ID IS NULL OR NEW.ID = 0) THEN
    NEW.ID = GEN_ID(GEN_REGRAS_PROMOCAO_ID, 1);
END^
SET TERM ; ^

SET TERM ^ ;
-- PROCEDURE PARA ATIVAR
CREATE OR ALTER PROCEDURE SP_ATIVAR_PROMO_SECAO (VAR_SEC INTEGER)
AS
BEGIN
    -- Salva o preço original e aplica o promocional
    UPDATE PRODUTO 
    SET PRECO_NORMAL = PRECO_VAREJO,
        PRECO_VAREJO = PRECO_PROMOCAO
    WHERE COD_SEC = :VAR_SEC 
      AND PRECO_PROMOCAO > 0 
      AND (PRECO_NORMAL IS NULL OR PRECO_NORMAL = 0); -- Evita sobrescrever se já estiver em promo
END^

-- PROCEDURE PARA DESATIVAR
CREATE OR ALTER PROCEDURE SP_DESATIVAR_PROMO_SECAO (VAR_SEC INTEGER)
AS
BEGIN
    -- Volta o preço original e limpa o backup
    UPDATE PRODUTO 
    SET PRECO_VAREJO = PRECO_NORMAL,
        PRECO_NORMAL = NULL
    WHERE COD_SEC = :VAR_SEC 
      AND PRECO_NORMAL IS NOT NULL;
END^

SET TERM ; ^
